//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingRequest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qbit_info
    {
        public int info_id { get; set; }
        public string info_imei { get; set; }
        public string info_metadata { get; set; }
        public int info_timecreate { get; set; }
        public Nullable<System.DateTime> info_last_online { get; set; }
    }
}
