//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadingRequest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qbit_detail
    {
        public int detail_id { get; set; }
        public string detail_imei { get; set; }
        public string detail_lat { get; set; }
        public string detail_lng { get; set; }
        public string detail_speed { get; set; }
        public System.DateTime detail_time { get; set; }
        public System.DateTime detail_last { get; set; }
    }
}
